task: detection

num_classes: 5
remap_mscoco_category: False

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /kaggle/input/mobdrone-dataset-coco-format/mobdrone/images/train
    ann_file: /kaggle/input/mobdrone-dataset-coco-format/mobdrone/annotations/train.json
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  batch_size: 8
  num_workers: 4
  drop_last: True

val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /kaggle/input/mobdrone-dataset-coco-format/mobdrone/images/valid
    ann_file: /kaggle/input/mobdrone-dataset-coco-format/mobdrone/annotations/val.json
    transforms:
      type: Compose
      ops: ~

  shuffle: False
  batch_size: 8
  num_workers: 4
  drop_last: False



